import os
import json
import sys
from typing import Dict, Any

# Ensure Python can look at the current folder for imports
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Import your execution pipeline directly from the local folder
from savings_planner import run_agent3_pipeline

# Mock data reflecting outputs from Agent 1 and Agent 2
mock_agent1_data = {
    "income": 50000, 
    "expense": 36000, 
    "food": 8500, 
    "shopping": 7000, 
    "subscriptions": 1800, 
    "emi": 6000, 
    "disposable_income": 14000
}

mock_agent2_data = {
    "financial_score": 68, 
    "health_level": "Average", 
    "strengths": ["Stable income", "Low EMI"], 
    "weaknesses": ["Low savings", "High shopping", "Frequent food delivery"]
}

mock_user_intent = {
    "goal": "Laptop", 
    "target_amount": 80000, 
    "timeline_months": 10
}

def execute_local_agent_test():
    print("=" * 70)
    print("  RUNNING LOCAL AGENT 3 ISOLATED TEST PANEL  ")
    print("=" * 70)
    
    if not os.environ.get("GEMINI_API_KEY"):
        print("\n[CRITICAL ERROR] Execution Halted: Missing GEMINI_API_KEY!")
        print("-> Please run your environment export/set command first.\n")
        return

    print("[INFO] Triggering calculations and LLM workflow inside agent3 folder...\n")
    
    try:
        structured_json_response = run_agent3_pipeline(
            agent1_json=mock_agent1_data, 
            agent2_json=mock_agent2_data, 
            user_goal_json=mock_user_intent
        )
        
        print("\n" + "=" * 70)
        print("  SUCCESS: VALID STRATEGY ROADMAP TARGET GENERATED BY GEMINI ENGINE  ")
        print("=" * 70)
        print(structured_json_response)
        
    except Exception as e:
        print(f"\n[RUN RUNTIME BREAKDOWN] Operational trace failed: {str(e)}")

if __name__ == "__main__":
    execute_local_agent_test()
    